version: '3.8'
services:
  dev-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  test-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env.test
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    ports:
      - '5435:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    restart: always
    depends_on:
      - dev-db

volumes:
  postgres-data:
  postgres-test-data:
  redis:
